name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'publishAar.sh'
      - 'docker/**'
  pull_request:

permissions:
  contents: write

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - linux-arm64
          - linux-x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Disk Cleanup
        run: ./disk_cleanup.sh
      - name: Setup
        run: sudo scripts/apt_install.sh
      - name: Build
        run: make -C build ${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos-arm64
          - macos-x64
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make -C build USE_CCACHE=0 ${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Disk Cleanup
        run: .\disk_cleanup.bat
      - name: Build
        run: powershell -NoProfile -ExecutionPolicy Unrestricted .\build.windows.ps1
        shell: pwsh
      - name: Upload artifact x64
        uses: actions/upload-artifact@v3
        with:
          name: libwebrtc-win-x64.7z
          path: package/libwebrtc-win-x64.7z
      - name: Upload artifact x86
        uses: actions/upload-artifact@v3
        with:
          name: libwebrtc-win-x86.7z
          path: package/libwebrtc-win-x86.7z


  
